### ISSUE TITLE
E-Mail-Adressen als CSS-Klasse anlegen (rückwärts lesen)

### ISSUE THREAD

**Issue by JockelK** [codeformuenster/alternative-skulptur-projekte#16]

**Comment by ubergesundheit** [comment]
HTML tags nach diesem Format:
```html
<a data-href="moc.elpmaxe@liame:otliam" class="obfusmail" rel="nofollow">moc.elpmaxe@liame</a>
```
Mit diesem CSS
```css
.obfusmail {
  unicode-bidi: bidi-override;
  direction: rtl;
}
```
und diesem Javascript:
```js
document.addEventListener("DOMContentLoaded", function () {
  var links = document.querySelectorAll(".obfusmail");
  for (var i = 0; i < links.length; i++) {
    var link = links[i];
    var address = link.dataset.href;
    link.href = address.split('').reverse().join('');
  }
})
```
